### GET root
GET http://localhost:5179/
Accept: application/json

###

### GET all users
GET http://localhost:5179/users
Accept: application/json

###

### POST new user
POST http://localhost:5179/signup
Content-Type: application/json

{
  "name": "hady",
  "email": "hady@example.com",
  "passwordHash": "hadySecurePassword123"
}

###

### POST duplicate email (should fail)
POST http://localhost:5179/signup
Content-Type: application/json

{
  "name": "Duplicate",
  "email": "abdulla@example.com",
  "passwordHash": "AnotherPassword456"
}

###

### GET user by ID 
GET http://localhost:5179/users/9b57d29d-8565-420c-a959-3b4bdc166750
Accept: application/json

###

### GET user by email
GET http://localhost:5179/users/by-email/hady@example.com
Accept: application/json

###

### SEARCH users by name
GET http://localhost:5179/users/search?name=ha
Accept: application/json

###

### PUT update user 
PUT http://localhost:5179/users/9b57d29d-8565-420c-a959-3b4bdc166750
Content-Type: application/json

{
  "name": "hady Updated",
  "email": "hady.updated@example.com",
  "passwordHash": "hadySecurePassword789"
}

###

### PUT with same password (should fail)
PUT http://localhost:5179/users/9b57d29d-8565-420c-a959-3b4bdc166750
Content-Type: application/json

{
  "name": "hady Updated2",
  "email": "hady2.updated@example.com",
  "passwordHash": "hadySecurePassword123"
}

###

### DELETE user (replace ID)
DELETE http://localhost:5179/users/ac4ab1cb-6408-4c26-87d0-c9c7bf430931

###

### LOGIN with correct credentials
POST http://localhost:5179/login
Content-Type: application/json

{
  "email": "abdulla@example.com",
  "password": "MySecurePassword123"
}

###

### LOGIN with wrong password (should fail)
POST http://localhost:5179/login
Content-Type: application/json

{
  "email": "abdulla@example.com",
  "password": "WrongPassword"
}